/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdditionalRequests = IDL.Record({
  'needsMule' : IDL.Bool,
  'needsHotelPostTrek' : IDL.Bool,
  'needsPickup' : IDL.Bool,
  'specialAssistance' : IDL.Text,
  'hearAboutUs' : IDL.Text,
  'needsPorter' : IDL.Bool,
  'hotelPreNights' : IDL.Nat,
  'needsHotelPreTrek' : IDL.Bool,
  'hotelPostNights' : IDL.Nat,
});
export const HealthDetails = IDL.Record({
  'dietaryRequirements' : IDL.Text,
  'hasMedicalCondition' : IDL.Bool,
  'trekedAbove3500m' : IDL.Bool,
  'comfortableWalking6to8h' : IDL.Bool,
  'medicalConditionDetails' : IDL.Text,
  'tshirtSize' : IDL.Text,
});
export const PersonalDetails = IDL.Record({
  'dob' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'emergencyContactRelation' : IDL.Text,
  'gender' : IDL.Text,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'additionalRequests' : AdditionalRequests,
  'submittedAt' : IDL.Int,
  'children' : IDL.Nat,
  'healthDetails' : HealthDetails,
  'personalDetails' : PersonalDetails,
  'trekName' : IDL.Text,
  'trekSlug' : IDL.Text,
  'adults' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'batchDate' : IDL.Text,
});
export const BookingInput = IDL.Record({
  'additionalRequests' : AdditionalRequests,
  'children' : IDL.Nat,
  'healthDetails' : HealthDetails,
  'personalDetails' : PersonalDetails,
  'trekName' : IDL.Text,
  'trekSlug' : IDL.Text,
  'adults' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'batchDate' : IDL.Text,
});
export const BookingResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ReviewInput = IDL.Record({
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'email' : IDL.Text,
  'trekDate' : IDL.Text,
  'trekSlug' : IDL.Text,
  'rating' : IDL.Nat,
  'yatraSlug' : IDL.Text,
});
export const ReviewResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func([BookingInput], [BookingResult], []),
  'submitReview' : IDL.Func([ReviewInput], [ReviewResult], []),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdditionalRequests = IDL.Record({
    'needsMule' : IDL.Bool,
    'needsHotelPostTrek' : IDL.Bool,
    'needsPickup' : IDL.Bool,
    'specialAssistance' : IDL.Text,
    'hearAboutUs' : IDL.Text,
    'needsPorter' : IDL.Bool,
    'hotelPreNights' : IDL.Nat,
    'needsHotelPreTrek' : IDL.Bool,
    'hotelPostNights' : IDL.Nat,
  });
  const HealthDetails = IDL.Record({
    'dietaryRequirements' : IDL.Text,
    'hasMedicalCondition' : IDL.Bool,
    'trekedAbove3500m' : IDL.Bool,
    'comfortableWalking6to8h' : IDL.Bool,
    'medicalConditionDetails' : IDL.Text,
    'tshirtSize' : IDL.Text,
  });
  const PersonalDetails = IDL.Record({
    'dob' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'emergencyContactRelation' : IDL.Text,
    'gender' : IDL.Text,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'additionalRequests' : AdditionalRequests,
    'submittedAt' : IDL.Int,
    'children' : IDL.Nat,
    'healthDetails' : HealthDetails,
    'personalDetails' : PersonalDetails,
    'trekName' : IDL.Text,
    'trekSlug' : IDL.Text,
    'adults' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'batchDate' : IDL.Text,
  });
  const BookingInput = IDL.Record({
    'additionalRequests' : AdditionalRequests,
    'children' : IDL.Nat,
    'healthDetails' : HealthDetails,
    'personalDetails' : PersonalDetails,
    'trekName' : IDL.Text,
    'trekSlug' : IDL.Text,
    'adults' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'batchDate' : IDL.Text,
  });
  const BookingResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ReviewInput = IDL.Record({
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'email' : IDL.Text,
    'trekDate' : IDL.Text,
    'trekSlug' : IDL.Text,
    'rating' : IDL.Nat,
    'yatraSlug' : IDL.Text,
  });
  const ReviewResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func([BookingInput], [BookingResult], []),
    'submitReview' : IDL.Func([ReviewInput], [ReviewResult], []),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };