/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdditionalRequests {
  'needsMule' : boolean,
  'needsHotelPostTrek' : boolean,
  'needsPickup' : boolean,
  'specialAssistance' : string,
  'hearAboutUs' : string,
  'needsPorter' : boolean,
  'hotelPreNights' : bigint,
  'needsHotelPreTrek' : boolean,
  'hotelPostNights' : bigint,
}
export interface Booking {
  'id' : string,
  'additionalRequests' : AdditionalRequests,
  'submittedAt' : bigint,
  'children' : bigint,
  'healthDetails' : HealthDetails,
  'personalDetails' : PersonalDetails,
  'trekName' : string,
  'trekSlug' : string,
  'adults' : bigint,
  'totalPrice' : bigint,
  'batchDate' : string,
}
export interface BookingInput {
  'additionalRequests' : AdditionalRequests,
  'children' : bigint,
  'healthDetails' : HealthDetails,
  'personalDetails' : PersonalDetails,
  'trekName' : string,
  'trekSlug' : string,
  'adults' : bigint,
  'totalPrice' : bigint,
  'batchDate' : string,
}
export type BookingResult = { 'ok' : string } |
  { 'err' : string };
export interface HealthDetails {
  'dietaryRequirements' : string,
  'hasMedicalCondition' : boolean,
  'trekedAbove3500m' : boolean,
  'comfortableWalking6to8h' : boolean,
  'medicalConditionDetails' : string,
  'tshirtSize' : string,
}
export interface PersonalDetails {
  'dob' : string,
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'emergencyContactRelation' : string,
  'gender' : string,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
}
export interface ReviewInput {
  'reviewText' : string,
  'reviewerName' : string,
  'email' : string,
  'trekDate' : string,
  'trekSlug' : string,
  'rating' : bigint,
  'yatraSlug' : string,
}
export type ReviewResult = { 'ok' : string } |
  { 'err' : string };
export interface _SERVICE {
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'submitBooking' : ActorMethod<[BookingInput], BookingResult>,
  'submitReview' : ActorMethod<[ReviewInput], ReviewResult>,
  'transform' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];